// Need to use the React-specific entry point to import `createApi`
import { createEntityAdapter } from "@reduxjs/toolkit"
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"

type Quote = {
  id: number
  quote: string
  author: string
}

type QuotesApiResponse = {
  quotes: Quote[]
  total: number
  skip: number
  limit: number
}

// 创建 adapter，用于 normalization
const quotesAdapter = createEntityAdapter<Quote>({
  // 按作者名排序
  sortComparer: (a, b) => a.author.localeCompare(b.author),
})

// 获取初始 normalized 状态
const initialState = quotesAdapter.getInitialState()

// 额外的元数据（total, skip, limit）可以单独存储
type AdditionalQuotesState = {
  total: number
  skip: number
  limit: number
}

// 完整的 normalized 返回类型
type NormalizedQuotesResponse = ReturnType<typeof quotesAdapter.getInitialState> & AdditionalQuotesState

// Define a service using a base URL and expected endpoints
export const quotesApiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: "https://dummyjson.com/quotes" }),
  reducerPath: "quotesApi",
  // Tag types are used for caching and invalidation.
  tagTypes: ["Quotes"],
  endpoints: build => ({
    // Supply generics for the return type (in this case the normalized shape)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    getQuotes: build.query<NormalizedQuotesResponse, number>({
      query: (limit = 10) => `?limit=${limit.toString()}`,
      // transformResponse 将 API 返回的数组数据 normalized 为 { ids, entities } 结构
      transformResponse: (response: QuotesApiResponse) => {
        return {
          ...quotesAdapter.setAll(initialState, response.quotes),
          total: response.total,
          skip: response.skip,
          limit: response.limit,
        }
      },
      // `providesTags` determines which 'tag' is attached to the
      // cached data returned by the query.
      providesTags: (result) =>
        result
          ? [
              ...result.ids.map(id => ({ type: "Quotes" as const, id })),
              { type: "Quotes", id: "LIST" },
            ]
          : [{ type: "Quotes", id: "LIST" }],
    }),
  }),
})

// 导出 adapter 的 selectors，方便在组件中使用
export const quotesSelectors = quotesAdapter.getSelectors()

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const { useGetQuotesQuery } = quotesApiSlice
